### ISSUE TITLE
Responsive CSS: .span5-7 classes

### ISSUE THREAD

**Issue by francoisjacquet** [PremiseWP/Premise-WP#17]
@mvallejo3 using `.span6` in my plugin settings grid, the result looks like this at 320px wide:
![screenshot from 2015-12-10 17 38 00](https://cloud.githubusercontent.com/assets/4723501/11730751/01680a0a-9f65-11e5-8c98-fcdd3861c699.png)

Less than 150px wide for select inputs & labels is too short.
Should I apply the [same responsive CSS rules for the .span-5-7 classes](https://github.com/PremiseWP/Premise-WP/blob/master/css/source/premise-responsive.css#L108)?

**Comment by mvallejo3** [comment]
No. Leave this like this for now. We can discuss next week. I rather let the theme or plugin control what happens to those classes on responsive. I am not opposed to changing it but we have to consider all the scenarios.
