### ISSUE TITLE
Premise checkbox field label not styled as other fields

### ISSUE THREAD

**Issue by francoisjacquet** [PremiseWP/Premise-WP#2]
Please see screenshot:
![screenshot from 2015-11-10 15 22 23](https://cloud.githubusercontent.com/assets/4723501/11074721/24f596f8-87bf-11e5-9810-87cdc9b673f4.png)

**Comment by mvallejo3** [comment]
This is the design we had originally picked. I agree that we should reconsider design on radio and checkbox fields to make it more consistent across fields. I'll work on that.

**Comment by mvallejo3** [comment]
fixed. screenshot: https://www.dropbox.com/s/kceaynsgdlu4bky/Screenshot%202015-11-11%2001.34.00.png?dl=0

**Comment by francoisjacquet** [comment]
Thank you for the screenshot.
There must have been a misunderstanding, I was talking about the checkbox **label**, not the checkbox in itself which indeed was like in the picked design.
