### ISSUE TITLE
Multiple premiseGoogleMap on the same page

### ISSUE THREAD

**Issue by francoisjacquet** [PremiseWP/Premise-WP#33]
@mvallejo3 
I have been writing some tests (see [premise-demo](https://github.com/PremiseWP/premise-demo/commit/275991c031dd3efc3308f3b09c144602f0bb35c9)) for the new jQuery premiseGoogleMap plugin.
Only the last Google Map on the page is displayed.

It seems the problem lies in the fact that the other Google Maps fail to be created because the Google Maps API (JS file) has not loaded yet.

My intent to make them wait for the JS script to be ready was unsuccessful.

**Comment by francoisjacquet** [comment]
The issue is still here I am afraid.
@mvallejo3 I have updated the `Premise-WP.min.js` file with your last commit and checked the [premise-demo](https://github.com/PremiseWP/premise-demo/commit/275991c031dd3efc3308f3b09c144602f0bb35c9) tests again:

![screen shot 2016-10-07 at 10 34 12](https://cloud.githubusercontent.com/assets/4723501/19183671/b7839bd6-8c79-11e6-9f37-e274131e3386.png)

**Comment by mvallejo3** [comment]
![screen shot 2016-10-07 at 8 09 12 am](https://cloud.githubusercontent.com/assets/11527707/19190865/64ab666e-8c65-11e6-9b9b-dacd7a051a13.png)

**Comment by mvallejo3** [comment]
we now use roamiGmap. premiseGoogleMap has been deprecated
